### ISSUE TITLE
Trying to build debian package from source

### ISSUE THREAD

**Issue by eddybl** [dls-controls/pythonSoftIOC#45]
Hey,

I am trying to build the softioc from source to create a debian package.

I am able to build the dependencies from source:
* setuptools-dso
* epicscorelibs
* epicsdbbuilder

But during the build process for softioc I run into the following exception:
```
RuntimeError: Unable to find DSO epicscorelibs.lib.qsrv needed by extension softioc._extension
```

More detailed log:
```
dpkg-buildpackage: info: source package softioc
dpkg-buildpackage: info: source version 3.2-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Michael Abbott <Michael.Abbott@diamond.ac.uk>
dpkg-buildpackage: info: host architecture amd64
dpkg-source: info: using options from softioc-3.2/debian/source/options: --extend-diff-ignore=\.egg-info$
dh build --with python3 --buildsystem=python_distutils
   dh_update_autotools_config -O--buildsystem=python_distutils
   dh_auto_configure -O--buildsystem=python_distutils
   debian/rules override_dh_auto_build
make[1]: Entering directory '/builds/python-tools/deb-builder/deb_dist/softioc-3.2'
python3 setup.py build --force
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.8
creating build/lib.linux-x86_64-3.8/softioc
copying softioc/__main__.py -> build/lib.linux-x86_64-3.8/softioc
copying softioc/fields.py -> build/lib.linux-x86_64-3.8/softioc
copying softioc/builder.py -> build/lib.linux-x86_64-3.8/softioc
copying softioc/alarm.py -> build/lib.linux-x86_64-3.8/softioc
copying softioc/softioc.py -> build/lib.linux-x86_64-3.8/softioc
copying softioc/device.py -> build/lib.linux-x86_64-3.8/softioc
copying softioc/pythonSoftIoc.py -> build/lib.linux-x86_64-3.8/softioc
copying softioc/asyncio_dispatcher.py -> build/lib.linux-x86_64-3.8/softioc
copying softioc/_version_git.py -> build/lib.linux-x86_64-3.8/softioc
copying softioc/imports.py -> build/lib.linux-x86_64-3.8/softioc
copying softioc/__init__.py -> build/lib.linux-x86_64-3.8/softioc
copying softioc/device_core.py -> build/lib.linux-x86_64-3.8/softioc
copying softioc/pvlog.py -> build/lib.linux-x86_64-3.8/softioc
copying softioc/access.acf -> build/lib.linux-x86_64-3.8/softioc
copying softioc/device.dbd -> build/lib.linux-x86_64-3.8/softioc
copying softioc/devIocStats.dbd -> build/lib.linux-x86_64-3.8/softioc
creating build/lib.linux-x86_64-3.8/softioc/iocStatsDb
copying softioc/iocStatsDb/iocAdminVxWorks.substitutions -> build/lib.linux-x86_64-3.8/softioc/iocStatsDb
copying softioc/iocStatsDb/iocScanMonSum.template -> build/lib.linux-x86_64-3.8/softioc/iocStatsDb
copying softioc/iocStatsDb/iocAdminScanMon.substitutions -> build/lib.linux-x86_64-3.8/softioc/iocStatsDb
copying softioc/iocStatsDb/iocCluster.template -> build/lib.linux-x86_64-3.8/softioc/iocStatsDb
copying softioc/iocStatsDb/iocScanMon.template -> build/lib.linux-x86_64-3.8/softioc/iocStatsDb
copying softioc/iocStatsDb/iocRTEMSOnly.template -> build/lib.linux-x86_64-3.8/softioc/iocStatsDb
copying softioc/iocStatsDb/iocQueue.db -> build/lib.linux-x86_64-3.8/softioc/iocStatsDb
copying softioc/iocStatsDb/iocGeneralTime.template -> build/lib.linux-x86_64-3.8/softioc/iocStatsDb
copying softioc/iocStatsDb/Makefile -> build/lib.linux-x86_64-3.8/softioc/iocStatsDb
copying softioc/iocStatsDb/iocVxWorksOnly.template -> build/lib.linux-x86_64-3.8/softioc/iocStatsDb
copying softioc/iocStatsDb/iocAdminSoft.substitutions -> build/lib.linux-x86_64-3.8/softioc/iocStatsDb
copying softioc/iocStatsDb/iocAdminRTEMS.substitutions -> build/lib.linux-x86_64-3.8/softioc/iocStatsDb
copying softioc/iocStatsDb/iocRTOS.template -> build/lib.linux-x86_64-3.8/softioc/iocStatsDb
copying softioc/iocStatsDb/access.doc -> build/lib.linux-x86_64-3.8/softioc/iocStatsDb
copying softioc/iocStatsDb/access.db -> build/lib.linux-x86_64-3.8/softioc/iocStatsDb
copying softioc/iocStatsDb/iocEnvVar.template -> build/lib.linux-x86_64-3.8/softioc/iocStatsDb
copying softioc/iocStatsDb/ioc.template -> build/lib.linux-x86_64-3.8/softioc/iocStatsDb
running build_ext
make[1]: Leaving directory '/builds/python-tools/deb-builder/deb_dist/softioc-3.2'


Standard error:
dpkg-buildpackage: warning: using a gain-root-command while being root
 dpkg-source --before-build .
 debian/rules build
dh_auto_configure: warning: Please use the third-party "pybuild" build system instead of python-distutils
dh_auto_configure: warning: This feature will be removed in compat 12.
Traceback (most recent call last):
  File "setup.py", line 103, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools_dso/__init__.py", line 58, in setup
    _setup(**kws)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools_dso/dsocmd.py", line 511, in run
    _build_ext.run(self)
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3/dist-packages/setuptools_dso/dsocmd.py", line 522, in build_extension
    self.dso2lib_pre(ext)
  File "/usr/lib/python3/dist-packages/setuptools_dso/dsocmd.py", line 169, in dso2lib_pre
    raise RuntimeError("Unable to find DSO %s needed by extension %s"%(dso, ext.name))
RuntimeError: Unable to find DSO epicscorelibs.lib.qsrv needed by extension softioc._extension
make[1]: *** [debian/rules:14: override_dh_auto_build] Error 1
make: *** [debian/rules:7: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
```

I also tried to install epics base first, but it did not help. Any advice?

**Comment by mdavidsaver** [comment]
I need more information about the Debian package being used for the python modules `setuptools-dso`, `epicscorelibs`, and `softioc`.

Are these separate debian packages, or bundled in some way?

If separate, are both `setuptools-dso` and `epicscorelibs` listed as a `Build-Depends` of `softioc`?

The search path for DSOs is computed [here](https://github.com/mdavidsaver/setuptools_dso/blob/dfd9d55fedf01f356969700d75c67a03a030e50a/src/setuptools_dso/dsocmd.py#L150-L158) as the current build directory (eg. `build/lib.*/`), and perhaps the result of `import_module('epicscorelibs').__file__`.

Issues with the setuptools_dso may be reported [here](https://github.com/mdavidsaver/setuptools_dso/issues).

**Comment by mdavidsaver** [comment]
Can you share a link to the debian packaging?

I'm specifically interested in the file list for the `epicscorelibs` binary package(s).

Does a `softioc` build succeed if run outside of a debian build environment, with dependencies install as deb. packages?

That is, running something like `./setup.py build_ext` as a regular user?

> If I understand the code correctly, it does not try to look up the file in the `lib` subfolder

In this case `parts[1:-1]` should evaluate to `['lib']`.  So using your paths:

```py
                # parts should be ['epicscorelibs', 'lib', 'qsrv'] so...
                dsobase = os.path.dirname(import_module(parts[0]).__file__)
                # dosbase should be "/usr/lib/python3/dist-packages/epicscorelibs"
                dsodir = os.path.join(dsobase, *parts[1:-1])
                # dsodir should be "/usr/lib/python3/dist-packages/epicscorelibs/lib"
```

Does `/usr/lib/python3/dist-packages/epicscorelibs/lib/libqsrv.so` exist?

You could add some prints in `.../setuptools_dso/dsocmd.py` to verify this.

fyi. The `log.debug()` lines are activated by eg. `./setup.py -v bdist_wheel` with the `-v` _before_ the command.

Also, please set `export DH_VERBOSE=1` to get more useful output from the debhelper builds.  eg. which arguments are passed to setup.py.

**Comment by mdavidsaver** [comment]
> libCom.cpython-38-x86_64-linux-gnu.so

I suspect that one of the `dh_*` helper scripts is making the reasonable, but in this case incorrect, assumption that every `.so` in a python tree is a C extension, then automatically "fixing" the file names.

If this is the case, then the log produced by running a debian build with `export DH_VERBOSE=1` should indicate this.  (in my experience the debhelper scripts are good about logging any changes made)

**Comment by mdavidsaver** [comment]
The `py2dsc` script crates three files which constitute the debian source package.  There are a great many tools/workflows for editing a source package.  I would recommend `git-buildpackage` and `pristine-tar` in combination.  Taking the setuptools-dso package as a self-contained example, this looks like:

```sh
pypi-download setuptools-dso
py2dsc setuptools_dso-2.3.tar.gz
mkdir setuptools_dso
cd setuptools_dso/
git init
gbp import-dsc ../deb_dist/setuptools-dso_2.3-1.dsc
gbp pristine-tar commit ../deb_dist/setuptools-dso_2.3.orig.tar.gz
```

Then edit `debian/rules` and add a target `override_dh_python3`.

```
#!/usr/bin/make -f
export PYBUILD_NAME=setuptools-dso
%:
        dh $@ --with python3 --buildsystem=pybuild

# ... Add the following ...
override_dh_python3:
        dh_python3 --no-ext-rename
```

Then commit and build with

```
git add -u
git ci -m 'override dh_python3 --no-ext-rename'
gbp buildpackage --git-pristine-tar
```

If all goes well...

```
dpkg-deb -c ../python3-setuptools-dso_2.3-1_all.deb
```

**Comment by eddybl** [comment]
I was able to apply the patch and have verified that the libs now have the correct name. The build of softioc now continues, but fails at a later point in time. The full log is here: https://gist.github.com/eddybl/f35643886622de9a3c5cb50c58a7e4b4

The last few lines are:
```
fakeroot debian/rules binary
D: dh_python3 dh_python3:161: version: 4.20191017ubuntu7
D: dh_python3 dh_python3:162: argv: ['/usr/bin/dh_python3', '-O--buildsystem=python_distutils']
D: dh_python3 dh_python3:163: options: {'guess_deps': True, 'skip_private': False, 'verbose': False, 'arch': None, 'package': None, 'no_package': None, 'compile_all': False, 'vrange': None, 'regexpr': None, 'accept_upstream_versions': False, 'depends': None, 'depends_section': None, 'recommends': None, 'recommends_section': None, 'suggests': None, 'suggests_section': None, 'requires': None, 'shebang': None, 'ignore_shebangs': False, 'clean_dbg_pkg': True, 'no_ext_rename': False, 'no_shebang_rewrite': False, 'O': '--buildsystem=python_distutils'}
D: dh_python3 dh_python3:164: args: []
D: dh_python3 dh_python3:165: supported Python versions: 3.8 (default=3.8)
D: dh_python3 debhelper:152: source=softioc, binary packages=['python3-softioc']
D: dh_python3 dh_python3:183: processing package python3-softioc...
I: dh_python3 fs:394: renaming softioc-3.2-py3.8.egg-info to softioc-3.2.egg-info
D: dh_python3 fs:260: package python3-softioc details = {'requires.txt': {'debian/python3-softioc/usr/lib/python3/dist-packages/softioc-3.2.egg-info/requires.txt'}, 'egg-info': set(), 'nsp.txt': set(), 'shebangs': {/usr/bin/python3}, 'public_vers': {Version('3')}, 'private_dirs': {}, 'compile': True, 'ext_vers': {Version('3.8')}, 'ext_no_version': set()}
D: dh_python3 depends:117: generating dependencies for package python3-softioc
D: dh_python3 pydist:137: trying to find dependency for epicscorelibs<7.0.6.99.2,>=7.0.6.99.1.0 (python=None)
D: dh_python3 pydist:205: invoking dpkg -S *python3/*/[Ee][Pp][Ii][Cc][Ss][Cc][Oo][Rr][Ee][Ll][Ii][Bb][Ss]-?*\.egg-info
D: dh_python3 pydist:137: trying to find dependency for numpy (python=None)
D: dh_python3 pydist:137: trying to find dependency for epicsdbbuilder>=1.4 (python=None)
D: dh_python3 pydist:205: invoking dpkg -S *python3/*/[Ee][Pp][Ii][Cc][Ss][Dd][Bb][Bb][Uu][Ii][Ll][Dd][Ee][Rr]-?*\.egg-info
D: dh_python3 depends:275: D={'python3-epicscorelibs', 'python3-epicsdbbuilder', 'python3-numpy', 'python3 (<< 3.9)', 'python3:any', 'python3 (>= 3.8~)'}; R=[]; S=[]; E=[], B=[]; RT=[]
dpkg-shlibdeps: error: cannot find library libdbCore.so.7.0.6.99.1 needed by debian/python3-softioc/usr/lib/python3/dist-packages/softioc/_extension.cpython-38-x86_64-linux-gnu.so (ELF format: 'elf64-x86-64' abi: '0201003e00000000'; RPATH: '\/usr/lib/python3/dist-packages/softioc/../epicscorelibs/lib:/usr/lib/python3/dist-packages/softioc/../epicscorelibs/lib')
dpkg-shlibdeps: error: cannot find library libCom.so.7.0.6.99.1 needed by debian/python3-softioc/usr/lib/python3/dist-packages/softioc/_extension.cpython-38-x86_64-linux-gnu.so (ELF format: 'elf64-x86-64' abi: '0201003e00000000'; RPATH: '\/usr/lib/python3/dist-packages/softioc/../epicscorelibs/lib:/usr/lib/python3/dist-packages/softioc/../epicscorelibs/lib')
dpkg-shlibdeps: error: cannot continue due to the errors listed above
Note: libraries are not searched in other binary packages that do not have any shlibs or symbols file.
To help dpkg-shlibdeps find private libraries, you might need to use -l.
dh_shlibdeps: error: dpkg-shlibdeps -Tdebian/python3-softioc.substvars debian/python3-softioc/usr/lib/python3/dist-packages/softioc/_extension.cpython-38-x86_64-linux-gnu.so returned exit code 2
dh_shlibdeps: error: Aborting due to earlier error
make: *** [debian/rules:7: binary] Error 25
```

The actual files exsit at the correct location, but I am bit confused about the:
```
[...] RPATH: '\/usr/lib/python3/dist-packages/softioc/../epicscorelibs/lib:/usr/lib/python3/dist-packages/softioc/../epicscorelibs/lib')
```
since the /usr/lib/python3/dist-packages/softioc/ is at this point is not existing yet and therefore the relative import */softioc/../epicscorelibs/lib/* fails?

**Comment by mdavidsaver** [comment]
```
...
Note: libraries are not searched in other binary packages that do not have any shlibs or symbols file.
To help dpkg-shlibdeps find private libraries, you might need to use -l.
...
```

It might be enough to tell `dh_shlibdeps` where to find libCom et al.

```make
override_dh_shlibdeps:
        dh_shlibdeps -l/usr/lib/python3/dist-packages/epicscorelibs/lib
```
